# database connection with postgreSql
spring.datasource.url=jdbc:postgresql://localhost:5432/authentication
spring.datasource.username=postgres
spring.datasource.password=marie123
spring.datasource.driver-class-name=org.postgresql.Driver

# hibernate dialect / JPA(Java Persistence API) configuration
# "update" : hibernate will automatically create/alter the database tables based on the entity classes
# note: never use "update"/ "create" in production, use "validate" instead
spring.jpa.hibernate.ddl-auto=update

# show sql statements in the console. very useful for debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# hibernate dialect for postgreSql. it is important to set the correct dialect for your database, 
# otherwise hibernate will not generate the correct SQL statements
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect